### ISSUE TITLE
Render component in iframe

### ISSUE THREAD

**Issue by ngocsangyem** [evilkiwi/embed#2]
**Question:**
Could we dynamic render component in iframe by using embed?

**Solution:**
I suggest using slots feature in Vue.
Example: https://codesandbox.io/s/hf1fe

**Comment by devlsh** [comment]
Thanks for opening an issue!

`@evilkiwi/embed` is purely for IPC between two sources - the sort of feature you're asking for is too out-of-scope unfortunately.
